### ISSUE TITLE
for production

### ISSUE THREAD

**Issue by kernel164** [nmcclain/glauth#1]
Hi, I was searching for simple and good ldap proxy/server. I found this. Thanks for your work.
Can it be used in production? and is it stable ? Have you used in production - it supports tls that a good thing. The project description has "its for developers", so I just want to make sure that it can be used for production. 
This project seems 1 year old and hope you are still maintaining. kindly try to reply as soon as possible. Thanks in advance.

**Comment by nmcclain** [comment]
This is a hobby project and not supported for production use, sorry!
