### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by leenaars** [nmcclain/glauth#3]
Hi,

seems like a very interesting project.

I was wondering under which license this is being made available?
Do you recommend using this, or your other LDAP project?

**Comment by benyanke** [comment]
GPL?

**Comment by digininja** [comment]
Also want to know what licence. I want to use a very cut down and hacked up version of this in a tool I'm building that will be GPL.

**Comment by nmcclain** [comment]
I lean towards an Apache or BSD license to encourage the widest adoption - are you okay with that @benyanke ?

**Comment by digininja** [comment]
Does that mean it can be included in an app that is released under GPL? All source is there and credits and references to the original.

**Comment by benyanke** [comment]
That's what I'm looking at right now, @digininja digininja - I'd prefer a wide license which is still GPL compatible as well.

If anyone knows the best license for this, chime in!

**Comment by benyanke** [comment]
Looks like BSD and apache are not GPL-compatible, but 'Modified BSD' is?

https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD

**Comment by benyanke** [comment]
Looks like Apache 2 is [GPL compatible](https://www.gnu.org/licenses/license-list.en.html#apache2).

Let's go with that then @nmcclain ?

**Comment by nmcclain** [comment]
I was just looking at this (courtesy Github): https://choosealicense.com/

I have zero patent interests here, so maybe the MIT license is really the best fit?  I'm definitely down with Apache 2 as well...

**Comment by benyanke** [comment]
Sure - that works for me too. I'm good as long as it stays GPL compatible - that'll allow it to be the most flexible.

MIT it is!

**Comment by digininja** [comment]
My app is only GPL because it was the one I ticked when I created the
github project. It is all going out for free to do anything with so I don't
mind changing.

**Comment by nmcclain** [comment]
Does this look ok to you @benyanke ?

**Comment by benyanke** [comment]
👍

**Comment by digininja** [comment]
Thanks.
