### ISSUE TITLE
Add Configuration Option to Allow Annon Binding 

### ISSUE THREAD

**Issue by woopstar** [nmcclain/glauth#5]
This needs to allow anon access to RootDSE for it to work as authentication backend for SSSd in CoreOS etc.

When you use SSSd it fails as it is not allowed to do an anon binding on the RootDSE

**Comment by woopstar** [comment]
Or it should allow you to create a bind user for non-anon access btw

**Comment by benyanke** [comment]
> Or it should allow you to create a bind user for non-anon access btw

You can easily do that by just creating a user for the purpose of allowing binding, right?

**Comment by benyanke** [comment]
I do agree though - adding a boolean to allow annon binding would be good.

**Comment by benyanke** [comment]
This issue was moved to glauth/glauth#5
